dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - python setup.py develop
  - pip install codecov coverage
# command to run tests
script: ./travis_tests.sh
after_success:
  codecov
